package ORM;
// Generated Mar 26, 2018 12:50:47 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Brands generated by hbm2java
 */
public class Brands  implements java.io.Serializable {


     private Integer idBrands;
     private String brandName;
     private String isActive;
     private Set items = new HashSet(0);

    public Brands() {
    }

    public Brands(String brandName, String isActive, Set items) {
       this.brandName = brandName;
       this.isActive = isActive;
       this.items = items;
    }
   
    public Integer getIdBrands() {
        return this.idBrands;
    }
    
    public void setIdBrands(Integer idBrands) {
        this.idBrands = idBrands;
    }
    public String getBrandName() {
        return this.brandName;
    }
    
    public void setBrandName(String brandName) {
        this.brandName = brandName;
    }
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }
    public Set getItems() {
        return this.items;
    }
    
    public void setItems(Set items) {
        this.items = items;
    }




}


