package ORM;
// Generated Mar 26, 2018 12:50:47 AM by Hibernate Tools 4.3.1



/**
 * CashBook generated by hbm2java
 */
public class CashBook  implements java.io.Serializable {


     private Integer idCashBook;
     private Double credit;
     private Double debit;
     private String cbdate;
     private String descriotion;

    public CashBook() {
    }

    public CashBook(Double credit, Double debit, String cbdate, String descriotion) {
       this.credit = credit;
       this.debit = debit;
       this.cbdate = cbdate;
       this.descriotion = descriotion;
    }
   
    public Integer getIdCashBook() {
        return this.idCashBook;
    }
    
    public void setIdCashBook(Integer idCashBook) {
        this.idCashBook = idCashBook;
    }
    public Double getCredit() {
        return this.credit;
    }
    
    public void setCredit(Double credit) {
        this.credit = credit;
    }
    public Double getDebit() {
        return this.debit;
    }
    
    public void setDebit(Double debit) {
        this.debit = debit;
    }
    public String getCbdate() {
        return this.cbdate;
    }
    
    public void setCbdate(String cbdate) {
        this.cbdate = cbdate;
    }
    public String getDescriotion() {
        return this.descriotion;
    }
    
    public void setDescriotion(String descriotion) {
        this.descriotion = descriotion;
    }




}


