package ORM;
// Generated Mar 26, 2018 12:50:47 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Catogory generated by hbm2java
 */
public class Catogory  implements java.io.Serializable {


     private Integer idCatogory;
     private String catogoryCode;
     private String catogoryName;
     private String isActive;
     private Set items = new HashSet(0);

    public Catogory() {
    }

    public Catogory(String catogoryCode, String catogoryName, String isActive, Set items) {
       this.catogoryCode = catogoryCode;
       this.catogoryName = catogoryName;
       this.isActive = isActive;
       this.items = items;
    }
   
    public Integer getIdCatogory() {
        return this.idCatogory;
    }
    
    public void setIdCatogory(Integer idCatogory) {
        this.idCatogory = idCatogory;
    }
    public String getCatogoryCode() {
        return this.catogoryCode;
    }
    
    public void setCatogoryCode(String catogoryCode) {
        this.catogoryCode = catogoryCode;
    }
    public String getCatogoryName() {
        return this.catogoryName;
    }
    
    public void setCatogoryName(String catogoryName) {
        this.catogoryName = catogoryName;
    }
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }
    public Set getItems() {
        return this.items;
    }
    
    public void setItems(Set items) {
        this.items = items;
    }




}


