package ORM;
// Generated Mar 26, 2018 12:50:47 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Customers generated by hbm2java
 */
public class Customers  implements java.io.Serializable {


     private Integer idCustomers;
     private String customersNic;
     private String customerscolName;
     private String customersAddress1;
     private String customersAddress2;
     private String customersCity;
     private String customersContactNo;
     private String isActive;
     private Set invoicePaymentses = new HashSet(0);
     private Set invoiceHasCustomerses = new HashSet(0);
     private Set customersHasInvoiceReturns = new HashSet(0);

    public Customers() {
    }

    public Customers(String customersNic, String customerscolName, String customersAddress1, String customersAddress2, String customersCity, String customersContactNo, String isActive, Set invoicePaymentses, Set invoiceHasCustomerses, Set customersHasInvoiceReturns) {
       this.customersNic = customersNic;
       this.customerscolName = customerscolName;
       this.customersAddress1 = customersAddress1;
       this.customersAddress2 = customersAddress2;
       this.customersCity = customersCity;
       this.customersContactNo = customersContactNo;
       this.isActive = isActive;
       this.invoicePaymentses = invoicePaymentses;
       this.invoiceHasCustomerses = invoiceHasCustomerses;
       this.customersHasInvoiceReturns = customersHasInvoiceReturns;
    }
   
    public Integer getIdCustomers() {
        return this.idCustomers;
    }
    
    public void setIdCustomers(Integer idCustomers) {
        this.idCustomers = idCustomers;
    }
    public String getCustomersNic() {
        return this.customersNic;
    }
    
    public void setCustomersNic(String customersNic) {
        this.customersNic = customersNic;
    }
    public String getCustomerscolName() {
        return this.customerscolName;
    }
    
    public void setCustomerscolName(String customerscolName) {
        this.customerscolName = customerscolName;
    }
    public String getCustomersAddress1() {
        return this.customersAddress1;
    }
    
    public void setCustomersAddress1(String customersAddress1) {
        this.customersAddress1 = customersAddress1;
    }
    public String getCustomersAddress2() {
        return this.customersAddress2;
    }
    
    public void setCustomersAddress2(String customersAddress2) {
        this.customersAddress2 = customersAddress2;
    }
    public String getCustomersCity() {
        return this.customersCity;
    }
    
    public void setCustomersCity(String customersCity) {
        this.customersCity = customersCity;
    }
    public String getCustomersContactNo() {
        return this.customersContactNo;
    }
    
    public void setCustomersContactNo(String customersContactNo) {
        this.customersContactNo = customersContactNo;
    }
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }
    public Set getInvoicePaymentses() {
        return this.invoicePaymentses;
    }
    
    public void setInvoicePaymentses(Set invoicePaymentses) {
        this.invoicePaymentses = invoicePaymentses;
    }
    public Set getInvoiceHasCustomerses() {
        return this.invoiceHasCustomerses;
    }
    
    public void setInvoiceHasCustomerses(Set invoiceHasCustomerses) {
        this.invoiceHasCustomerses = invoiceHasCustomerses;
    }
    public Set getCustomersHasInvoiceReturns() {
        return this.customersHasInvoiceReturns;
    }
    
    public void setCustomersHasInvoiceReturns(Set customersHasInvoiceReturns) {
        this.customersHasInvoiceReturns = customersHasInvoiceReturns;
    }




}


