package ORM;
// Generated Mar 26, 2018 12:50:47 AM by Hibernate Tools 4.3.1



/**
 * CustomersHasInvoiceReturn generated by hbm2java
 */
public class CustomersHasInvoiceReturn  implements java.io.Serializable {


     private Integer idRecord;
     private Customers customers;
     private InvoiceReturn invoiceReturn;

    public CustomersHasInvoiceReturn() {
    }

    public CustomersHasInvoiceReturn(Customers customers, InvoiceReturn invoiceReturn) {
       this.customers = customers;
       this.invoiceReturn = invoiceReturn;
    }
   
    public Integer getIdRecord() {
        return this.idRecord;
    }
    
    public void setIdRecord(Integer idRecord) {
        this.idRecord = idRecord;
    }
    public Customers getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Customers customers) {
        this.customers = customers;
    }
    public InvoiceReturn getInvoiceReturn() {
        return this.invoiceReturn;
    }
    
    public void setInvoiceReturn(InvoiceReturn invoiceReturn) {
        this.invoiceReturn = invoiceReturn;
    }




}


