package ORM;
// Generated Mar 26, 2018 12:50:47 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Grn generated by hbm2java
 */
public class Grn  implements java.io.Serializable {


     private Integer idGrn;
     private Supplier supplier;
     private String grnno;
     private String grndate;
     private Double subTotal;
     private Double discount;
     private Double nettTotal;
     private String isActive;
     private String photo;
     private Set grnitems = new HashSet(0);
     private Set grnpaymentses = new HashSet(0);
     private Set itemSereals = new HashSet(0);

    public Grn() {
    }

	
    public Grn(Supplier supplier) {
        this.supplier = supplier;
    }
    public Grn(Supplier supplier, String grnno, String grndate, Double subTotal, Double discount, Double nettTotal, String isActive, String photo, Set grnitems, Set grnpaymentses, Set itemSereals) {
       this.supplier = supplier;
       this.grnno = grnno;
       this.grndate = grndate;
       this.subTotal = subTotal;
       this.discount = discount;
       this.nettTotal = nettTotal;
       this.isActive = isActive;
       this.photo = photo;
       this.grnitems = grnitems;
       this.grnpaymentses = grnpaymentses;
       this.itemSereals = itemSereals;
    }
   
    public Integer getIdGrn() {
        return this.idGrn;
    }
    
    public void setIdGrn(Integer idGrn) {
        this.idGrn = idGrn;
    }
    public Supplier getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
    }
    public String getGrnno() {
        return this.grnno;
    }
    
    public void setGrnno(String grnno) {
        this.grnno = grnno;
    }
    public String getGrndate() {
        return this.grndate;
    }
    
    public void setGrndate(String grndate) {
        this.grndate = grndate;
    }
    public Double getSubTotal() {
        return this.subTotal;
    }
    
    public void setSubTotal(Double subTotal) {
        this.subTotal = subTotal;
    }
    public Double getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Double discount) {
        this.discount = discount;
    }
    public Double getNettTotal() {
        return this.nettTotal;
    }
    
    public void setNettTotal(Double nettTotal) {
        this.nettTotal = nettTotal;
    }
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }
    public Set getGrnitems() {
        return this.grnitems;
    }
    
    public void setGrnitems(Set grnitems) {
        this.grnitems = grnitems;
    }
    public Set getGrnpaymentses() {
        return this.grnpaymentses;
    }
    
    public void setGrnpaymentses(Set grnpaymentses) {
        this.grnpaymentses = grnpaymentses;
    }
    public Set getItemSereals() {
        return this.itemSereals;
    }
    
    public void setItemSereals(Set itemSereals) {
        this.itemSereals = itemSereals;
    }




}


