package ORM;
// Generated Mar 26, 2018 12:50:47 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Grnitem generated by hbm2java
 */
public class Grnitem  implements java.io.Serializable {


     private Integer idGrnitem;
     private Grn grn;
     private Item item;
     private Integer qty;
     private Double grossPrice;
     private Double total;
     private Set supplierReturns = new HashSet(0);

    public Grnitem() {
    }

	
    public Grnitem(Grn grn, Item item) {
        this.grn = grn;
        this.item = item;
    }
    public Grnitem(Grn grn, Item item, Integer qty, Double grossPrice, Double total, Set supplierReturns) {
       this.grn = grn;
       this.item = item;
       this.qty = qty;
       this.grossPrice = grossPrice;
       this.total = total;
       this.supplierReturns = supplierReturns;
    }
   
    public Integer getIdGrnitem() {
        return this.idGrnitem;
    }
    
    public void setIdGrnitem(Integer idGrnitem) {
        this.idGrnitem = idGrnitem;
    }
    public Grn getGrn() {
        return this.grn;
    }
    
    public void setGrn(Grn grn) {
        this.grn = grn;
    }
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }
    public Double getGrossPrice() {
        return this.grossPrice;
    }
    
    public void setGrossPrice(Double grossPrice) {
        this.grossPrice = grossPrice;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }
    public Set getSupplierReturns() {
        return this.supplierReturns;
    }
    
    public void setSupplierReturns(Set supplierReturns) {
        this.supplierReturns = supplierReturns;
    }




}


