package ORM;
// Generated Mar 26, 2018 12:50:47 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Invoice generated by hbm2java
 */
public class Invoice  implements java.io.Serializable {


     private Integer idInvoice;
     private String invoiceNo;
     private String invoiceDate;
     private Double subTotal;
     private Double discount;
     private Double nettTotal;
     private String isActive;
     private String createdBy;
     private Double paid;
     private Double balance;
     private Set invoiceItems = new HashSet(0);
     private Set invoiceReturns = new HashSet(0);
     private Set invoiceHasCustomerses = new HashSet(0);
     private Set invoicePaymentses = new HashSet(0);

    public Invoice() {
    }

    public Invoice(String invoiceNo, String invoiceDate, Double subTotal, Double discount, Double nettTotal, String isActive, String createdBy, Double paid, Double balance, Set invoiceItems, Set invoiceReturns, Set invoiceHasCustomerses, Set invoicePaymentses) {
       this.invoiceNo = invoiceNo;
       this.invoiceDate = invoiceDate;
       this.subTotal = subTotal;
       this.discount = discount;
       this.nettTotal = nettTotal;
       this.isActive = isActive;
       this.createdBy = createdBy;
       this.paid = paid;
       this.balance = balance;
       this.invoiceItems = invoiceItems;
       this.invoiceReturns = invoiceReturns;
       this.invoiceHasCustomerses = invoiceHasCustomerses;
       this.invoicePaymentses = invoicePaymentses;
    }
   
    public Integer getIdInvoice() {
        return this.idInvoice;
    }
    
    public void setIdInvoice(Integer idInvoice) {
        this.idInvoice = idInvoice;
    }
    public String getInvoiceNo() {
        return this.invoiceNo;
    }
    
    public void setInvoiceNo(String invoiceNo) {
        this.invoiceNo = invoiceNo;
    }
    public String getInvoiceDate() {
        return this.invoiceDate;
    }
    
    public void setInvoiceDate(String invoiceDate) {
        this.invoiceDate = invoiceDate;
    }
    public Double getSubTotal() {
        return this.subTotal;
    }
    
    public void setSubTotal(Double subTotal) {
        this.subTotal = subTotal;
    }
    public Double getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Double discount) {
        this.discount = discount;
    }
    public Double getNettTotal() {
        return this.nettTotal;
    }
    
    public void setNettTotal(Double nettTotal) {
        this.nettTotal = nettTotal;
    }
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Double getPaid() {
        return this.paid;
    }
    
    public void setPaid(Double paid) {
        this.paid = paid;
    }
    public Double getBalance() {
        return this.balance;
    }
    
    public void setBalance(Double balance) {
        this.balance = balance;
    }
    public Set getInvoiceItems() {
        return this.invoiceItems;
    }
    
    public void setInvoiceItems(Set invoiceItems) {
        this.invoiceItems = invoiceItems;
    }
    public Set getInvoiceReturns() {
        return this.invoiceReturns;
    }
    
    public void setInvoiceReturns(Set invoiceReturns) {
        this.invoiceReturns = invoiceReturns;
    }
    public Set getInvoiceHasCustomerses() {
        return this.invoiceHasCustomerses;
    }
    
    public void setInvoiceHasCustomerses(Set invoiceHasCustomerses) {
        this.invoiceHasCustomerses = invoiceHasCustomerses;
    }
    public Set getInvoicePaymentses() {
        return this.invoicePaymentses;
    }
    
    public void setInvoicePaymentses(Set invoicePaymentses) {
        this.invoicePaymentses = invoicePaymentses;
    }




}


