package ORM;
// Generated Mar 26, 2018 12:50:47 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * InvoiceItem generated by hbm2java
 */
public class InvoiceItem  implements java.io.Serializable {


     private Integer idInvoiceItem;
     private Invoice invoice;
     private Item item;
     private Integer qty;
     private Double unitPrice;
     private Double discount;
     private Double nettTotalItm;
     private String isActive;
     private String warranry;
     private Set itemSerealHasInvoiceItems = new HashSet(0);
     private Set invoiceReturns = new HashSet(0);

    public InvoiceItem() {
    }

	
    public InvoiceItem(Invoice invoice, Item item) {
        this.invoice = invoice;
        this.item = item;
    }
    public InvoiceItem(Invoice invoice, Item item, Integer qty, Double unitPrice, Double discount, Double nettTotalItm, String isActive, String warranry, Set itemSerealHasInvoiceItems, Set invoiceReturns) {
       this.invoice = invoice;
       this.item = item;
       this.qty = qty;
       this.unitPrice = unitPrice;
       this.discount = discount;
       this.nettTotalItm = nettTotalItm;
       this.isActive = isActive;
       this.warranry = warranry;
       this.itemSerealHasInvoiceItems = itemSerealHasInvoiceItems;
       this.invoiceReturns = invoiceReturns;
    }
   
    public Integer getIdInvoiceItem() {
        return this.idInvoiceItem;
    }
    
    public void setIdInvoiceItem(Integer idInvoiceItem) {
        this.idInvoiceItem = idInvoiceItem;
    }
    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }
    public Double getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(Double unitPrice) {
        this.unitPrice = unitPrice;
    }
    public Double getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Double discount) {
        this.discount = discount;
    }
    public Double getNettTotalItm() {
        return this.nettTotalItm;
    }
    
    public void setNettTotalItm(Double nettTotalItm) {
        this.nettTotalItm = nettTotalItm;
    }
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }
    public String getWarranry() {
        return this.warranry;
    }
    
    public void setWarranry(String warranry) {
        this.warranry = warranry;
    }
    public Set getItemSerealHasInvoiceItems() {
        return this.itemSerealHasInvoiceItems;
    }
    
    public void setItemSerealHasInvoiceItems(Set itemSerealHasInvoiceItems) {
        this.itemSerealHasInvoiceItems = itemSerealHasInvoiceItems;
    }
    public Set getInvoiceReturns() {
        return this.invoiceReturns;
    }
    
    public void setInvoiceReturns(Set invoiceReturns) {
        this.invoiceReturns = invoiceReturns;
    }




}


