package ORM;
// Generated Mar 26, 2018 12:50:47 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * InvoiceReturn generated by hbm2java
 */
public class InvoiceReturn  implements java.io.Serializable {


     private Integer idInvoiceReturn;
     private Invoice invoice;
     private InvoiceItem invoiceItem;
     private String retuenDate;
     private Double returnQty;
     private String itemSerial;
     private String term;
     private String status;
     private String isActive;
     private String itemCondition;
     private Set customersHasInvoiceReturns = new HashSet(0);

    public InvoiceReturn() {
    }

	
    public InvoiceReturn(Invoice invoice, InvoiceItem invoiceItem) {
        this.invoice = invoice;
        this.invoiceItem = invoiceItem;
    }
    public InvoiceReturn(Invoice invoice, InvoiceItem invoiceItem, String retuenDate, Double returnQty, String itemSerial, String term, String status, String isActive, String itemCondition, Set customersHasInvoiceReturns) {
       this.invoice = invoice;
       this.invoiceItem = invoiceItem;
       this.retuenDate = retuenDate;
       this.returnQty = returnQty;
       this.itemSerial = itemSerial;
       this.term = term;
       this.status = status;
       this.isActive = isActive;
       this.itemCondition = itemCondition;
       this.customersHasInvoiceReturns = customersHasInvoiceReturns;
    }
   
    public Integer getIdInvoiceReturn() {
        return this.idInvoiceReturn;
    }
    
    public void setIdInvoiceReturn(Integer idInvoiceReturn) {
        this.idInvoiceReturn = idInvoiceReturn;
    }
    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }
    public InvoiceItem getInvoiceItem() {
        return this.invoiceItem;
    }
    
    public void setInvoiceItem(InvoiceItem invoiceItem) {
        this.invoiceItem = invoiceItem;
    }
    public String getRetuenDate() {
        return this.retuenDate;
    }
    
    public void setRetuenDate(String retuenDate) {
        this.retuenDate = retuenDate;
    }
    public Double getReturnQty() {
        return this.returnQty;
    }
    
    public void setReturnQty(Double returnQty) {
        this.returnQty = returnQty;
    }
    public String getItemSerial() {
        return this.itemSerial;
    }
    
    public void setItemSerial(String itemSerial) {
        this.itemSerial = itemSerial;
    }
    public String getTerm() {
        return this.term;
    }
    
    public void setTerm(String term) {
        this.term = term;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }
    public String getItemCondition() {
        return this.itemCondition;
    }
    
    public void setItemCondition(String itemCondition) {
        this.itemCondition = itemCondition;
    }
    public Set getCustomersHasInvoiceReturns() {
        return this.customersHasInvoiceReturns;
    }
    
    public void setCustomersHasInvoiceReturns(Set customersHasInvoiceReturns) {
        this.customersHasInvoiceReturns = customersHasInvoiceReturns;
    }




}


