package ORM;
// Generated Mar 26, 2018 12:50:47 AM by Hibernate Tools 4.3.1



/**
 * InvoicePayments generated by hbm2java
 */
public class InvoicePayments  implements java.io.Serializable {


     private Integer idInvoicePayment;
     private Customers customers;
     private Invoice invoice;
     private String paymentDate;
     private Double amount;
     private String paymentType;
     private String isActive;

    public InvoicePayments() {
    }

	
    public InvoicePayments(Customers customers, Invoice invoice) {
        this.customers = customers;
        this.invoice = invoice;
    }
    public InvoicePayments(Customers customers, Invoice invoice, String paymentDate, Double amount, String paymentType, String isActive) {
       this.customers = customers;
       this.invoice = invoice;
       this.paymentDate = paymentDate;
       this.amount = amount;
       this.paymentType = paymentType;
       this.isActive = isActive;
    }
   
    public Integer getIdInvoicePayment() {
        return this.idInvoicePayment;
    }
    
    public void setIdInvoicePayment(Integer idInvoicePayment) {
        this.idInvoicePayment = idInvoicePayment;
    }
    public Customers getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Customers customers) {
        this.customers = customers;
    }
    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }
    public String getPaymentDate() {
        return this.paymentDate;
    }
    
    public void setPaymentDate(String paymentDate) {
        this.paymentDate = paymentDate;
    }
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }
    public String getPaymentType() {
        return this.paymentType;
    }
    
    public void setPaymentType(String paymentType) {
        this.paymentType = paymentType;
    }
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }




}


