package ORM;
// Generated Mar 26, 2018 12:50:47 AM by Hibernate Tools 4.3.1



/**
 * InvoiceHasCustomers generated by hbm2java
 */
public class InvoiceHasCustomers  implements java.io.Serializable {


     private Integer idIhc;
     private Customers customers;
     private Invoice invoice;

    public InvoiceHasCustomers() {
    }

    public InvoiceHasCustomers(Customers customers, Invoice invoice) {
       this.customers = customers;
       this.invoice = invoice;
    }
   
    public Integer getIdIhc() {
        return this.idIhc;
    }
    
    public void setIdIhc(Integer idIhc) {
        this.idIhc = idIhc;
    }
    public Customers getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Customers customers) {
        this.customers = customers;
    }
    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }




}


