package ORM;
// Generated Mar 26, 2018 12:50:47 AM by Hibernate Tools 4.3.1



/**
 * ItemPrices generated by hbm2java
 */
public class ItemPrices  implements java.io.Serializable {


     private Integer idItemPrices;
     private Item item;
     private Double grossPrice;
     private Double nettPrice;
     private Double minPrice;
     private String supWarrenty;
     private String selelrWarrenty;

    public ItemPrices() {
    }

	
    public ItemPrices(Item item) {
        this.item = item;
    }
    public ItemPrices(Item item, Double grossPrice, Double nettPrice, Double minPrice, String supWarrenty, String selelrWarrenty) {
       this.item = item;
       this.grossPrice = grossPrice;
       this.nettPrice = nettPrice;
       this.minPrice = minPrice;
       this.supWarrenty = supWarrenty;
       this.selelrWarrenty = selelrWarrenty;
    }
   
    public Integer getIdItemPrices() {
        return this.idItemPrices;
    }
    
    public void setIdItemPrices(Integer idItemPrices) {
        this.idItemPrices = idItemPrices;
    }
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }
    public Double getGrossPrice() {
        return this.grossPrice;
    }
    
    public void setGrossPrice(Double grossPrice) {
        this.grossPrice = grossPrice;
    }
    public Double getNettPrice() {
        return this.nettPrice;
    }
    
    public void setNettPrice(Double nettPrice) {
        this.nettPrice = nettPrice;
    }
    public Double getMinPrice() {
        return this.minPrice;
    }
    
    public void setMinPrice(Double minPrice) {
        this.minPrice = minPrice;
    }
    public String getSupWarrenty() {
        return this.supWarrenty;
    }
    
    public void setSupWarrenty(String supWarrenty) {
        this.supWarrenty = supWarrenty;
    }
    public String getSelelrWarrenty() {
        return this.selelrWarrenty;
    }
    
    public void setSelelrWarrenty(String selelrWarrenty) {
        this.selelrWarrenty = selelrWarrenty;
    }




}


