package ORM;
// Generated Mar 26, 2018 12:50:47 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Item generated by hbm2java
 */
public class Item  implements java.io.Serializable {


     private Integer idItem;
     private Brands brands;
     private Catogory catogory;
     private String itemCode;
     private String iitemName;
     private String isActive;
     private String descriotion;
     private String unit;
     private Set invoiceItems = new HashSet(0);
     private Set stocks = new HashSet(0);
     private Set itemPriceses = new HashSet(0);
     private Set itemSereals = new HashSet(0);
     private Set grnitems = new HashSet(0);
     private Set supplierInvoiceItems = new HashSet(0);

    public Item() {
    }

	
    public Item(Brands brands, Catogory catogory) {
        this.brands = brands;
        this.catogory = catogory;
    }
    public Item(Brands brands, Catogory catogory, String itemCode, String iitemName, String isActive, String descriotion, String unit, Set invoiceItems, Set stocks, Set itemPriceses, Set itemSereals, Set grnitems, Set supplierInvoiceItems) {
       this.brands = brands;
       this.catogory = catogory;
       this.itemCode = itemCode;
       this.iitemName = iitemName;
       this.isActive = isActive;
       this.descriotion = descriotion;
       this.unit = unit;
       this.invoiceItems = invoiceItems;
       this.stocks = stocks;
       this.itemPriceses = itemPriceses;
       this.itemSereals = itemSereals;
       this.grnitems = grnitems;
       this.supplierInvoiceItems = supplierInvoiceItems;
    }
   
    public Integer getIdItem() {
        return this.idItem;
    }
    
    public void setIdItem(Integer idItem) {
        this.idItem = idItem;
    }
    public Brands getBrands() {
        return this.brands;
    }
    
    public void setBrands(Brands brands) {
        this.brands = brands;
    }
    public Catogory getCatogory() {
        return this.catogory;
    }
    
    public void setCatogory(Catogory catogory) {
        this.catogory = catogory;
    }
    public String getItemCode() {
        return this.itemCode;
    }
    
    public void setItemCode(String itemCode) {
        this.itemCode = itemCode;
    }
    public String getIitemName() {
        return this.iitemName;
    }
    
    public void setIitemName(String iitemName) {
        this.iitemName = iitemName;
    }
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }
    public String getDescriotion() {
        return this.descriotion;
    }
    
    public void setDescriotion(String descriotion) {
        this.descriotion = descriotion;
    }
    public String getUnit() {
        return this.unit;
    }
    
    public void setUnit(String unit) {
        this.unit = unit;
    }
    public Set getInvoiceItems() {
        return this.invoiceItems;
    }
    
    public void setInvoiceItems(Set invoiceItems) {
        this.invoiceItems = invoiceItems;
    }
    public Set getStocks() {
        return this.stocks;
    }
    
    public void setStocks(Set stocks) {
        this.stocks = stocks;
    }
    public Set getItemPriceses() {
        return this.itemPriceses;
    }
    
    public void setItemPriceses(Set itemPriceses) {
        this.itemPriceses = itemPriceses;
    }
    public Set getItemSereals() {
        return this.itemSereals;
    }
    
    public void setItemSereals(Set itemSereals) {
        this.itemSereals = itemSereals;
    }
    public Set getGrnitems() {
        return this.grnitems;
    }
    
    public void setGrnitems(Set grnitems) {
        this.grnitems = grnitems;
    }
    public Set getSupplierInvoiceItems() {
        return this.supplierInvoiceItems;
    }
    
    public void setSupplierInvoiceItems(Set supplierInvoiceItems) {
        this.supplierInvoiceItems = supplierInvoiceItems;
    }




}


