package ORM;
// Generated Mar 26, 2018 12:50:47 AM by Hibernate Tools 4.3.1



/**
 * ItemSerealHasInvoiceItem generated by hbm2java
 */
public class ItemSerealHasInvoiceItem  implements java.io.Serializable {


     private Integer idRecord;
     private InvoiceItem invoiceItem;
     private ItemSereal itemSereal;

    public ItemSerealHasInvoiceItem() {
    }

    public ItemSerealHasInvoiceItem(InvoiceItem invoiceItem, ItemSereal itemSereal) {
       this.invoiceItem = invoiceItem;
       this.itemSereal = itemSereal;
    }
   
    public Integer getIdRecord() {
        return this.idRecord;
    }
    
    public void setIdRecord(Integer idRecord) {
        this.idRecord = idRecord;
    }
    public InvoiceItem getInvoiceItem() {
        return this.invoiceItem;
    }
    
    public void setInvoiceItem(InvoiceItem invoiceItem) {
        this.invoiceItem = invoiceItem;
    }
    public ItemSereal getItemSereal() {
        return this.itemSereal;
    }
    
    public void setItemSereal(ItemSereal itemSereal) {
        this.itemSereal = itemSereal;
    }




}


