package ORM;
// Generated Mar 26, 2018 12:50:47 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ItemSereal generated by hbm2java
 */
public class ItemSereal  implements java.io.Serializable {


     private Integer idItemSereal;
     private Grn grn;
     private Item item;
     private Supplier supplier;
     private String serealNo;
     private String isActive;
     private String status;
     private Set itemSerealHasInvoiceItems = new HashSet(0);
     private Set supplierInvoiceItemHasItemSereals = new HashSet(0);

    public ItemSereal() {
    }

	
    public ItemSereal(Grn grn, Item item, Supplier supplier) {
        this.grn = grn;
        this.item = item;
        this.supplier = supplier;
    }
    public ItemSereal(Grn grn, Item item, Supplier supplier, String serealNo, String isActive, String status, Set itemSerealHasInvoiceItems, Set supplierInvoiceItemHasItemSereals) {
       this.grn = grn;
       this.item = item;
       this.supplier = supplier;
       this.serealNo = serealNo;
       this.isActive = isActive;
       this.status = status;
       this.itemSerealHasInvoiceItems = itemSerealHasInvoiceItems;
       this.supplierInvoiceItemHasItemSereals = supplierInvoiceItemHasItemSereals;
    }
   
    public Integer getIdItemSereal() {
        return this.idItemSereal;
    }
    
    public void setIdItemSereal(Integer idItemSereal) {
        this.idItemSereal = idItemSereal;
    }
    public Grn getGrn() {
        return this.grn;
    }
    
    public void setGrn(Grn grn) {
        this.grn = grn;
    }
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }
    public Supplier getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
    }
    public String getSerealNo() {
        return this.serealNo;
    }
    
    public void setSerealNo(String serealNo) {
        this.serealNo = serealNo;
    }
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set getItemSerealHasInvoiceItems() {
        return this.itemSerealHasInvoiceItems;
    }
    
    public void setItemSerealHasInvoiceItems(Set itemSerealHasInvoiceItems) {
        this.itemSerealHasInvoiceItems = itemSerealHasInvoiceItems;
    }
    public Set getSupplierInvoiceItemHasItemSereals() {
        return this.supplierInvoiceItemHasItemSereals;
    }
    
    public void setSupplierInvoiceItemHasItemSereals(Set supplierInvoiceItemHasItemSereals) {
        this.supplierInvoiceItemHasItemSereals = supplierInvoiceItemHasItemSereals;
    }




}


