package ORM;
// Generated Mar 26, 2018 12:50:47 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Supplier generated by hbm2java
 */
public class Supplier  implements java.io.Serializable {


     private Integer idSupplier;
     private String supplierCode;
     private String supplierName;
     private String supplierAddress1;
     private String supplierAddress2;
     private String supplierCity;
     private String supplierContactNo1;
     private String supplierContactNo2;
     private String supplierEmail;
     private String isActive;
     private Set supplierInvoices = new HashSet(0);
     private Set supplierInvoicePaymentses = new HashSet(0);
     private Set supplierReturns = new HashSet(0);
     private Set grns = new HashSet(0);
     private Set grnpaymentses = new HashSet(0);
     private Set itemSereals = new HashSet(0);
     private Set supplierInvoiceReturnHasSuppliers = new HashSet(0);

    public Supplier() {
    }

    public Supplier(String supplierCode, String supplierName, String supplierAddress1, String supplierAddress2, String supplierCity, String supplierContactNo1, String supplierContactNo2, String supplierEmail, String isActive, Set supplierInvoices, Set supplierInvoicePaymentses, Set supplierReturns, Set grns, Set grnpaymentses, Set itemSereals, Set supplierInvoiceReturnHasSuppliers) {
       this.supplierCode = supplierCode;
       this.supplierName = supplierName;
       this.supplierAddress1 = supplierAddress1;
       this.supplierAddress2 = supplierAddress2;
       this.supplierCity = supplierCity;
       this.supplierContactNo1 = supplierContactNo1;
       this.supplierContactNo2 = supplierContactNo2;
       this.supplierEmail = supplierEmail;
       this.isActive = isActive;
       this.supplierInvoices = supplierInvoices;
       this.supplierInvoicePaymentses = supplierInvoicePaymentses;
       this.supplierReturns = supplierReturns;
       this.grns = grns;
       this.grnpaymentses = grnpaymentses;
       this.itemSereals = itemSereals;
       this.supplierInvoiceReturnHasSuppliers = supplierInvoiceReturnHasSuppliers;
    }
   
    public Integer getIdSupplier() {
        return this.idSupplier;
    }
    
    public void setIdSupplier(Integer idSupplier) {
        this.idSupplier = idSupplier;
    }
    public String getSupplierCode() {
        return this.supplierCode;
    }
    
    public void setSupplierCode(String supplierCode) {
        this.supplierCode = supplierCode;
    }
    public String getSupplierName() {
        return this.supplierName;
    }
    
    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName;
    }
    public String getSupplierAddress1() {
        return this.supplierAddress1;
    }
    
    public void setSupplierAddress1(String supplierAddress1) {
        this.supplierAddress1 = supplierAddress1;
    }
    public String getSupplierAddress2() {
        return this.supplierAddress2;
    }
    
    public void setSupplierAddress2(String supplierAddress2) {
        this.supplierAddress2 = supplierAddress2;
    }
    public String getSupplierCity() {
        return this.supplierCity;
    }
    
    public void setSupplierCity(String supplierCity) {
        this.supplierCity = supplierCity;
    }
    public String getSupplierContactNo1() {
        return this.supplierContactNo1;
    }
    
    public void setSupplierContactNo1(String supplierContactNo1) {
        this.supplierContactNo1 = supplierContactNo1;
    }
    public String getSupplierContactNo2() {
        return this.supplierContactNo2;
    }
    
    public void setSupplierContactNo2(String supplierContactNo2) {
        this.supplierContactNo2 = supplierContactNo2;
    }
    public String getSupplierEmail() {
        return this.supplierEmail;
    }
    
    public void setSupplierEmail(String supplierEmail) {
        this.supplierEmail = supplierEmail;
    }
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }
    public Set getSupplierInvoices() {
        return this.supplierInvoices;
    }
    
    public void setSupplierInvoices(Set supplierInvoices) {
        this.supplierInvoices = supplierInvoices;
    }
    public Set getSupplierInvoicePaymentses() {
        return this.supplierInvoicePaymentses;
    }
    
    public void setSupplierInvoicePaymentses(Set supplierInvoicePaymentses) {
        this.supplierInvoicePaymentses = supplierInvoicePaymentses;
    }
    public Set getSupplierReturns() {
        return this.supplierReturns;
    }
    
    public void setSupplierReturns(Set supplierReturns) {
        this.supplierReturns = supplierReturns;
    }
    public Set getGrns() {
        return this.grns;
    }
    
    public void setGrns(Set grns) {
        this.grns = grns;
    }
    public Set getGrnpaymentses() {
        return this.grnpaymentses;
    }
    
    public void setGrnpaymentses(Set grnpaymentses) {
        this.grnpaymentses = grnpaymentses;
    }
    public Set getItemSereals() {
        return this.itemSereals;
    }
    
    public void setItemSereals(Set itemSereals) {
        this.itemSereals = itemSereals;
    }
    public Set getSupplierInvoiceReturnHasSuppliers() {
        return this.supplierInvoiceReturnHasSuppliers;
    }
    
    public void setSupplierInvoiceReturnHasSuppliers(Set supplierInvoiceReturnHasSuppliers) {
        this.supplierInvoiceReturnHasSuppliers = supplierInvoiceReturnHasSuppliers;
    }




}


