package ORM;
// Generated Mar 26, 2018 12:50:47 AM by Hibernate Tools 4.3.1



/**
 * SupplierReturn generated by hbm2java
 */
public class SupplierReturn  implements java.io.Serializable {


     private Integer idSupplierReturn;
     private Grnitem grnitem;
     private Supplier supplier;
     private String retuenDate;
     private String returnQty;
     private String isActive;
     private String term;
     private String description;

    public SupplierReturn() {
    }

	
    public SupplierReturn(Grnitem grnitem, Supplier supplier) {
        this.grnitem = grnitem;
        this.supplier = supplier;
    }
    public SupplierReturn(Grnitem grnitem, Supplier supplier, String retuenDate, String returnQty, String isActive, String term, String description) {
       this.grnitem = grnitem;
       this.supplier = supplier;
       this.retuenDate = retuenDate;
       this.returnQty = returnQty;
       this.isActive = isActive;
       this.term = term;
       this.description = description;
    }
   
    public Integer getIdSupplierReturn() {
        return this.idSupplierReturn;
    }
    
    public void setIdSupplierReturn(Integer idSupplierReturn) {
        this.idSupplierReturn = idSupplierReturn;
    }
    public Grnitem getGrnitem() {
        return this.grnitem;
    }
    
    public void setGrnitem(Grnitem grnitem) {
        this.grnitem = grnitem;
    }
    public Supplier getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
    }
    public String getRetuenDate() {
        return this.retuenDate;
    }
    
    public void setRetuenDate(String retuenDate) {
        this.retuenDate = retuenDate;
    }
    public String getReturnQty() {
        return this.returnQty;
    }
    
    public void setReturnQty(String returnQty) {
        this.returnQty = returnQty;
    }
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }
    public String getTerm() {
        return this.term;
    }
    
    public void setTerm(String term) {
        this.term = term;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


