package ORM;
// Generated Mar 26, 2018 12:50:47 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SupplierInvoiceItem generated by hbm2java
 */
public class SupplierInvoiceItem  implements java.io.Serializable {


     private Integer idInvoiceItem;
     private Item item;
     private SupplierInvoice supplierInvoice;
     private Integer qty;
     private Double unitPrice;
     private Double discount;
     private Double nettTotalItm;
     private String isActive;
     private String warranry;
     private Set supplierInvoiceItemHasItemSereals = new HashSet(0);
     private Set supplierInvoiceReturns = new HashSet(0);

    public SupplierInvoiceItem() {
    }

	
    public SupplierInvoiceItem(Item item, SupplierInvoice supplierInvoice) {
        this.item = item;
        this.supplierInvoice = supplierInvoice;
    }
    public SupplierInvoiceItem(Item item, SupplierInvoice supplierInvoice, Integer qty, Double unitPrice, Double discount, Double nettTotalItm, String isActive, String warranry, Set supplierInvoiceItemHasItemSereals, Set supplierInvoiceReturns) {
       this.item = item;
       this.supplierInvoice = supplierInvoice;
       this.qty = qty;
       this.unitPrice = unitPrice;
       this.discount = discount;
       this.nettTotalItm = nettTotalItm;
       this.isActive = isActive;
       this.warranry = warranry;
       this.supplierInvoiceItemHasItemSereals = supplierInvoiceItemHasItemSereals;
       this.supplierInvoiceReturns = supplierInvoiceReturns;
    }
   
    public Integer getIdInvoiceItem() {
        return this.idInvoiceItem;
    }
    
    public void setIdInvoiceItem(Integer idInvoiceItem) {
        this.idInvoiceItem = idInvoiceItem;
    }
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }
    public SupplierInvoice getSupplierInvoice() {
        return this.supplierInvoice;
    }
    
    public void setSupplierInvoice(SupplierInvoice supplierInvoice) {
        this.supplierInvoice = supplierInvoice;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }
    public Double getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(Double unitPrice) {
        this.unitPrice = unitPrice;
    }
    public Double getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Double discount) {
        this.discount = discount;
    }
    public Double getNettTotalItm() {
        return this.nettTotalItm;
    }
    
    public void setNettTotalItm(Double nettTotalItm) {
        this.nettTotalItm = nettTotalItm;
    }
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }
    public String getWarranry() {
        return this.warranry;
    }
    
    public void setWarranry(String warranry) {
        this.warranry = warranry;
    }
    public Set getSupplierInvoiceItemHasItemSereals() {
        return this.supplierInvoiceItemHasItemSereals;
    }
    
    public void setSupplierInvoiceItemHasItemSereals(Set supplierInvoiceItemHasItemSereals) {
        this.supplierInvoiceItemHasItemSereals = supplierInvoiceItemHasItemSereals;
    }
    public Set getSupplierInvoiceReturns() {
        return this.supplierInvoiceReturns;
    }
    
    public void setSupplierInvoiceReturns(Set supplierInvoiceReturns) {
        this.supplierInvoiceReturns = supplierInvoiceReturns;
    }




}


