package ORM;
// Generated Mar 26, 2018 12:50:47 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SupplierInvoiceReturn generated by hbm2java
 */
public class SupplierInvoiceReturn  implements java.io.Serializable {


     private Integer idInvoiceReturn;
     private SupplierInvoice supplierInvoice;
     private SupplierInvoiceItem supplierInvoiceItem;
     private String retuenDate;
     private Double returnQty;
     private String itemSerial;
     private String term;
     private String status;
     private String isActive;
     private String itemCondition;
     private Set supplierInvoiceReturnHasSuppliers = new HashSet(0);

    public SupplierInvoiceReturn() {
    }

	
    public SupplierInvoiceReturn(SupplierInvoice supplierInvoice, SupplierInvoiceItem supplierInvoiceItem) {
        this.supplierInvoice = supplierInvoice;
        this.supplierInvoiceItem = supplierInvoiceItem;
    }
    public SupplierInvoiceReturn(SupplierInvoice supplierInvoice, SupplierInvoiceItem supplierInvoiceItem, String retuenDate, Double returnQty, String itemSerial, String term, String status, String isActive, String itemCondition, Set supplierInvoiceReturnHasSuppliers) {
       this.supplierInvoice = supplierInvoice;
       this.supplierInvoiceItem = supplierInvoiceItem;
       this.retuenDate = retuenDate;
       this.returnQty = returnQty;
       this.itemSerial = itemSerial;
       this.term = term;
       this.status = status;
       this.isActive = isActive;
       this.itemCondition = itemCondition;
       this.supplierInvoiceReturnHasSuppliers = supplierInvoiceReturnHasSuppliers;
    }
   
    public Integer getIdInvoiceReturn() {
        return this.idInvoiceReturn;
    }
    
    public void setIdInvoiceReturn(Integer idInvoiceReturn) {
        this.idInvoiceReturn = idInvoiceReturn;
    }
    public SupplierInvoice getSupplierInvoice() {
        return this.supplierInvoice;
    }
    
    public void setSupplierInvoice(SupplierInvoice supplierInvoice) {
        this.supplierInvoice = supplierInvoice;
    }
    public SupplierInvoiceItem getSupplierInvoiceItem() {
        return this.supplierInvoiceItem;
    }
    
    public void setSupplierInvoiceItem(SupplierInvoiceItem supplierInvoiceItem) {
        this.supplierInvoiceItem = supplierInvoiceItem;
    }
    public String getRetuenDate() {
        return this.retuenDate;
    }
    
    public void setRetuenDate(String retuenDate) {
        this.retuenDate = retuenDate;
    }
    public Double getReturnQty() {
        return this.returnQty;
    }
    
    public void setReturnQty(Double returnQty) {
        this.returnQty = returnQty;
    }
    public String getItemSerial() {
        return this.itemSerial;
    }
    
    public void setItemSerial(String itemSerial) {
        this.itemSerial = itemSerial;
    }
    public String getTerm() {
        return this.term;
    }
    
    public void setTerm(String term) {
        this.term = term;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }
    public String getItemCondition() {
        return this.itemCondition;
    }
    
    public void setItemCondition(String itemCondition) {
        this.itemCondition = itemCondition;
    }
    public Set getSupplierInvoiceReturnHasSuppliers() {
        return this.supplierInvoiceReturnHasSuppliers;
    }
    
    public void setSupplierInvoiceReturnHasSuppliers(Set supplierInvoiceReturnHasSuppliers) {
        this.supplierInvoiceReturnHasSuppliers = supplierInvoiceReturnHasSuppliers;
    }




}


