package ORM;
// Generated Mar 26, 2018 12:50:47 AM by Hibernate Tools 4.3.1



/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer idtable1;
     private String nic;
     private String name;
     private String userName;
     private String password;
     private String isActive;
     private String userType;

    public Users() {
    }

    public Users(String nic, String name, String userName, String password, String isActive, String userType) {
       this.nic = nic;
       this.name = name;
       this.userName = userName;
       this.password = password;
       this.isActive = isActive;
       this.userType = userType;
    }
   
    public Integer getIdtable1() {
        return this.idtable1;
    }
    
    public void setIdtable1(Integer idtable1) {
        this.idtable1 = idtable1;
    }
    public String getNic() {
        return this.nic;
    }
    
    public void setNic(String nic) {
        this.nic = nic;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }
    public String getUserType() {
        return this.userType;
    }
    
    public void setUserType(String userType) {
        this.userType = userType;
    }




}


