/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package srcs;

import ORM.Item;
import ORM.ItemPrices;
import Reports.ViewItemPrice;
import static Reports.ViewItemPrice.a;
import static Reports.ViewItemPrice.getID;
import static Reports.ViewItemPrice.ss;
import exClass.NotificationPopup;
import exClass.PoolManager;
import java.awt.Component;
import java.awt.event.KeyEvent;
import javax.swing.JTextField;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 *
 * @author oditha
 */
public class AddPrice extends javax.swing.JFrame {

    boolean FLAG_TXT_VALIDATE = false;

    public AddPrice() {
        initComponents();
        laodItemCode();
        txtGrossPrice.grabFocus();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtItemCode = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtGrossPrice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNettPrice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtMinPrice = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        comboSup = new javax.swing.JComboBox<String>();
        jLabel2 = new javax.swing.JLabel();
        comboSeller = new javax.swing.JComboBox<String>();
        txtSupWarrenty = new javax.swing.JTextField();
        txtSelelrWarrenty = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Price | JRTraders");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Item Code");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));

        txtItemCode.setEditable(false);
        txtItemCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemCodeActionPerformed(evt);
            }
        });
        jPanel1.add(txtItemCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 34, 190, -1));

        jLabel4.setText("Cost");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        txtGrossPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtGrossPriceFocusLost(evt);
            }
        });
        txtGrossPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGrossPriceKeyTyped(evt);
            }
        });
        jPanel1.add(txtGrossPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 190, -1));

        jLabel5.setText("Nett Price");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        txtNettPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNettPriceFocusLost(evt);
            }
        });
        txtNettPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNettPriceKeyTyped(evt);
            }
        });
        jPanel1.add(txtNettPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 190, -1));

        jLabel6.setText("Min Price");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        txtMinPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMinPriceFocusLost(evt);
            }
        });
        txtMinPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMinPriceKeyTyped(evt);
            }
        });
        jPanel1.add(txtMinPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 190, -1));

        jLabel1.setText("Supplier Warranty");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 133, -1, -1));

        comboSup.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Warranty", "Months", "Years" }));
        comboSup.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                comboSupPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        comboSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSupActionPerformed(evt);
            }
        });
        jPanel1.add(comboSup, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 155, -1, -1));

        jLabel2.setText("Seller Warranty");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 197, -1, -1));

        comboSeller.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Warranty", "Months", "Years" }));
        comboSeller.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                comboSellerPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jPanel1.add(comboSeller, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 220, -1, -1));

        txtSupWarrenty.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSupWarrentyFocusLost(evt);
            }
        });
        txtSupWarrenty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupWarrentyActionPerformed(evt);
            }
        });
        jPanel1.add(txtSupWarrenty, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 155, 190, -1));

        txtSelelrWarrenty.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSelelrWarrentyFocusLost(evt);
            }
        });
        jPanel1.add(txtSelelrWarrenty, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 220, 190, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtItemCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtItemCodeActionPerformed

    private void txtSupWarrentyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupWarrentyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupWarrentyActionPerformed

    private void comboSupPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_comboSupPopupMenuWillBecomeInvisible

//        if (comboSup.getSelectedIndex() == 0) {
//
//            txtSupWarrenty.setText("No Warranty");
//
//        } else {
//
//            txtSupWarrenty.setText(null);
//
//        }

    }//GEN-LAST:event_comboSupPopupMenuWillBecomeInvisible

    private void comboSellerPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_comboSellerPopupMenuWillBecomeInvisible

//        if (comboSeller.getSelectedIndex() == 0) {
//
//            txtSelelrWarrenty.setText("No Warranty");
//
//        } else {
//
//            txtSelelrWarrenty.setText(null);
//
//        }

    }//GEN-LAST:event_comboSellerPopupMenuWillBecomeInvisible

    private void txtGrossPriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtGrossPriceFocusLost
//        txtNettPrice.grabFocus();
    }//GEN-LAST:event_txtGrossPriceFocusLost

    private void txtNettPriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNettPriceFocusLost
//        txtMinPrice.grabFocus();
    }//GEN-LAST:event_txtNettPriceFocusLost

    private void txtMinPriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMinPriceFocusLost
//        txtSupWarrenty.grabFocus();
    }//GEN-LAST:event_txtMinPriceFocusLost

    private void txtSupWarrentyFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSupWarrentyFocusLost
//        txtSelelrWarrenty.grabFocus();
    }//GEN-LAST:event_txtSupWarrentyFocusLost

    private void txtSelelrWarrentyFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSelelrWarrentyFocusLost

//        btnSave.grabFocus();

    }//GEN-LAST:event_txtSelelrWarrentyFocusLost

    private void txtGrossPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGrossPriceKeyTyped
        char c = evt.getKeyChar();

        if (!((Character.isDigit(c)) || (c == KeyEvent.VK_PERIOD) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {

            evt.consume();

        }
    }//GEN-LAST:event_txtGrossPriceKeyTyped

    private void txtNettPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNettPriceKeyTyped
        char c = evt.getKeyChar();

        if (!((Character.isDigit(c)) || (c == KeyEvent.VK_PERIOD) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {

            evt.consume();

        }
    }//GEN-LAST:event_txtNettPriceKeyTyped

    private void txtMinPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMinPriceKeyTyped
        char c = evt.getKeyChar();

        if (!((Character.isDigit(c)) || (c == KeyEvent.VK_PERIOD) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {

            evt.consume();

        }
    }//GEN-LAST:event_txtMinPriceKeyTyped

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        try {
            System.out.println(a);
            if (FLAG_TXT_VALIDATE == false) {

                Session openSession = PoolManager.getSessionFactory().openSession();
                Transaction beginTransaction = openSession.beginTransaction();

                Item item=new Item();
                item.setIdItem(getID);
                ItemPrices ip = new ItemPrices();
                ip.setItem(item);
                ip.setGrossPrice(Double.parseDouble(txtGrossPrice.getText()));
                ip.setNettPrice(Double.parseDouble(txtNettPrice.getText()));
                ip.setMinPrice(Double.parseDouble(txtMinPrice.getText()));
                ip.setSupWarrenty(txtSupWarrenty.getText());
                ip.setSelelrWarrenty(txtSelelrWarrenty.getText());

                openSession.save(ip);
                beginTransaction.commit();
                openSession.close();

                NotificationPopup.save();
                ClearTXT();
                
                ViewItemPrice.loadPrice();
            } else {
                NotificationPopup.fillFeilds();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void comboSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboSupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddPrice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> comboSeller;
    private javax.swing.JComboBox<String> comboSup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtGrossPrice;
    private javax.swing.JTextField txtItemCode;
    private javax.swing.JTextField txtMinPrice;
    private javax.swing.JTextField txtNettPrice;
    private javax.swing.JTextField txtSelelrWarrenty;
    private javax.swing.JTextField txtSupWarrenty;
    // End of variables declaration//GEN-END:variables

    private void validateTXT() {

        if (txtGrossPrice.getText().isEmpty() && txtNettPrice.getText().isEmpty() && txtMinPrice.getText().isEmpty() && txtSupWarrenty.getText().isEmpty() && txtSelelrWarrenty.getText().isEmpty()) {
            FLAG_TXT_VALIDATE = true;
        } else {
            FLAG_TXT_VALIDATE = false;
        }

    }

    private void ClearTXT() {

        Component[] cp = jPanel1.getComponents();
        for (Component c : cp) {

            if (c instanceof JTextField) {

                ((JTextField) c).setText(null);

            }

        }

    }

    private void laodItemCode() {
        txtItemCode.setText(ss);
    }

}
