/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package srcs.CustomersAndInvoice;

import ORM.ItemPrices;
import ORM.Stock;
import exClass.PriceHolder;
import java.awt.print.PrinterException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import static srcs.CustomersAndInvoice.AddInvoicesV2.jTable1;

/**
 *
 * @author arshak
 */
public class ViewBarcordItem extends javax.swing.JFrame {

    /**
     * Creates new form ViewInvoiceSerials
     */
    public ViewBarcordItem() {
        initComponents();
        jTable1.setRowHeight(25);
        tableAlign();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("view Serial numbers | JRTraders");

        jTable1.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"ada", "ad", "ad", "ada", null, null}
            },
            new String [] {
                "ItemID", "Item Name", "Unit Price", "Unit", "MinPrice", "avbSTk"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(0);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(0);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
            jTable1.getColumnModel().getColumn(4).setMinWidth(0);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(0);
            jTable1.getColumnModel().getColumn(4).setMaxWidth(0);
            jTable1.getColumnModel().getColumn(5).setMinWidth(0);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(0);
            jTable1.getColumnModel().getColumn(5).setMaxWidth(0);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 883, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased


    }//GEN-LAST:event_jTable1MouseReleased

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased


    }//GEN-LAST:event_jTable1KeyReleased

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed

        if (evt.getKeyCode() == 10) {
            int selectedRow = jTable1.getSelectedRow();

            if (jTable1.getValueAt(selectedRow, 2).toString().equals("VARIATION")) {

                ViewPrice viewPrice = new ViewPrice();
                DefaultTableModel dtmP = (DefaultTableModel) viewPrice.jTable1.getModel();
                dtmP.setRowCount(0);
                System.out.println(AddInvoicesV2.itemprice.get(jTable1.getValueAt(selectedRow, 0).toString()));
                ArrayList<PriceHolder> get = AddInvoicesV2.itemprice.get(jTable1.getValueAt(selectedRow, 0).toString());
                System.out.println("List ON HEVEN-"+get);
                for (PriceHolder priceHolder : get) {

                    dtmP.addRow(new Object[]{
                        jTable1.getValueAt(selectedRow, 0),
                        jTable1.getValueAt(selectedRow, 1),
                        priceHolder.getUnitPrice(),
                        jTable1.getValueAt(selectedRow, 3),
                        priceHolder.getMinPrice(),
                        jTable1.getValueAt(selectedRow, 5),
                        });

                }

                viewPrice.jTable1.setRowSelectionInterval(0, 0);
                viewPrice.setVisible(true);
                dispose();

            } else {
                DefaultTableModel dtm = (DefaultTableModel) AddInvoicesV2.jTable1.getModel();

                dtm.addRow(new Object[]{
                    jTable1.getValueAt(selectedRow, 0),
                    jTable1.getValueAt(selectedRow, 1),
                    jTable1.getValueAt(selectedRow, 2),
                    1,
                    jTable1.getValueAt(selectedRow, 3),
                    jTable1.getValueAt(selectedRow, 2),
                    jTable1.getValueAt(selectedRow, 4),
                    jTable1.getValueAt(selectedRow, 5),});

                AddInvoicesV2.setGrnTotal();
                AddInvoicesV2.txtSerial.setText(null);
                AddInvoicesV2.txtSerial.grabFocus();
                dispose();
            }

        }

    }//GEN-LAST:event_jTable1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewBarcordItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewBarcordItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewBarcordItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewBarcordItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewBarcordItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

private void tableAlign() {

        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(JLabel.RIGHT);
        
        jTable1.getColumnModel().getColumn(2).setCellRenderer(rightRenderer);

    }


}
